#!/bin/bash

## Static site generator
# Dependencies: lowdown

title="Jayadeep's blog"

main() {
	test -n "$1" || usage

	h_file="src/_header.html"
	f_file="src/_footer.html"
	test -f "$f_file" && FOOTER=$(cat "$f_file") && export FOOTER
	test -f "$h_file" && HEADER=$(cat "$h_file") && export HEADER

  # Cleanup
  rm posts/*

  files=`ls src/*.md`
  for f in $files
  do
    basename $f | render_md_files_lowdown src posts
  done

  render_article_list "$files"

}

usage() {
	echo "usage: ${0##*/} render" >&2
	exit 1
}

render_md_files_lowdown() {
	while read -r f; do
		lowdown \
			--html-no-escapehtml \
			--html-no-skiphtml \
			--parse-no-metadata \
			--parse-no-autolink <"$1/$f" |
			render_html_file \
				>"$2/${f%\.md}.html"
	done
}

render_html_file() {
	awk -v title="$title" '
	{ body = body "\n" $0 }
	END {
		body = substr(body, 2)
		if (body ~ /<\/?[Hh][Tt][Mm][Ll]/) {
			print body
			exit
		}
		if (match(body, /<[[:space:]]*[Hh]1(>|[[:space:]][^>]*>)/)) {
			t = substr(body, RSTART + RLENGTH)
			sub("<[[:space:]]*/[[:space:]]*[Hh]1.*", "", t)
			gsub(/^[[:space:]]*|[[:space:]]$/, "", t)
			if (t) title = t " &mdash; " title
		}
		n = split(ENVIRON["HEADER"], header, /\n/)
		for (i = 1; i <= n; i++) {
			if (match(tolower(header[i]), "<title></title>")) {
				head = substr(header[i], 1, RSTART - 1)
				tail = substr(header[i], RSTART + RLENGTH)
				print head "<title>" title "</title>" tail
			} else print header[i]
		}
		print body
		print ENVIRON["FOOTER"]
	}'
}

get_articles() {
	urls="$1"
  sorted=""
  for url in $urls; do
    page_date=$(head -2 "$url" | tail -1)
    page_date=$(echo "$page_date" | sed 's/<[^>]*>//g')
    page_date=$(date -d "$page_date" +%s)
    u="$page_date:$url"
    sorted="$(echo -e "$sorted\n$u" | sort -r)"
    # li="<li><a href=\"$u\">$head</a></li>"
    # echo $li
  done

  for i in $sorted;do
    url=$(echo $i | cut -d: -f2-)

    page_title=$(head -n 1 "$url" | cut -c 3-)
    page_date=$(head -2 "$url" | tail -1)
    page_date=$(echo "$page_date" | sed 's/<[^>]*>//g')

    base=$(basename $url)
    post_url="/posts/${base/%\.md/\.html}"

    echo "<li><a href=\"$post_url\">$page_title</a><p class=\"date\">$page_date</p></li>"
  done
}

render_article_list() {
  articles=$(get_articles "$1")
  articles=$(echo $articles)

  sed -i "s|<ul class=\"articles\">.*</ul>|<ul class=\"articles\">${articles}</ul>|g" "index.html"
}

main "$@"
