name: ci

on:
  push:
    branches:
    - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get tag
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: "kmjayadeep/blog:latest,kmjayadeep/blog:${{ steps.vars.outputs.sha_short }}"
